server:
  port: 8080
spring:
  application:
    name: "Autenticacion"
  r2dbc:
    url: r2dbc:postgresql://postgres17_db:5432/autenticacion
    username: postgres
    password: postgres
    pool:
      initial-size: 1
      max-size: 5
      validation-query-timeout: 5s
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

routes:
  paths:
    create: "/api/v1/usuarios"

adapters:
  r2dbc:
    host: "postgres17_db"
    port: 5432
    database: "autenticacion"
    schema: "public"
    username: "postgres"
    password: "postgres"